### ISSUE TITLE
No tailwind conf file

### ISSUE THREAD

**Issue by sugarjohnny** [app-generator/rocket-flask#7]
Hi, when copying some flowbite ui elements i am instructed to edit the tailwind conf file, but i dont see it in the project

**Comment by app-generator** [comment]
Noted @sugarjohnny 

The set up will be migrated from [Rocket Django](https://github.com/app-generator/rocket-django)

- https://github.com/app-generator/rocket-django/blob/main/tailwind.config.js
- https://github.com/app-generator/rocket-django/blob/main/postcss.config.js
- https://github.com/app-generator/rocket-django/blob/main/package.json

Ping you back here once is done 

@mominur-helios please take a look and adapt the commands as for the Django version [ using the new paths ]: 

TY! 

```bash
$ npm install
$ npm run dev
$ npx tailwindcss -i ./static/assets/style.css -o ./static/dist/css/output.css --watch
```

**Comment by mominur-helios** [comment]
Hello @sugarjohnny ,

Tailwind config file is added you just need to run this following commands
```
$ npm install
$ npm run dev
```

Thank you!

**Comment by sugarjohnny** [comment]
Thanks
